name: Run Tests

on:
  push:
    paths:
      - '**.js'
      - '.github/workflows/run-tests.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [20,23]  # Specify Node.js versions to test
        npm: [9,10]      # Specify npm versions to test
    name: Test Node.js${{ matrix.node }} and npm${{ matrix.npm }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: List Installed Dependencies
        run: npm list --depth=0

      - name: Execute tests
        run: npm test -- --ci --verbose
